bc5cdr:
  data_files:
    - name: 'train'
      uri: 'https://ftp.ncbi.nlm.nih.gov/pub/lu/BC5CDR/CDR_TrainingSet.PubTator.txt'

    - name: 'validation'
      uri: 'https://ftp.ncbi.nlm.nih.gov/pub/lu/BC5CDR/CDR_DevelopmentSet.PubTator.txt'

    - name: 'test'
      uri: 'https://ftp.ncbi.nlm.nih.gov/pub/lu/BC5CDR/CDR_TestSet.PubTator.txt'

ncbi-disease:
  data_files:
    - name: 'train'
      uri: 'https://www.ncbi.nlm.nih.gov/CBBresearch/Dogan/DISEASE/NCBItrainset_corpus.zip'

    - name: 'validation'
      uri: 'https://www.ncbi.nlm.nih.gov/CBBresearch/Dogan/DISEASE/NCBIdevelopset_corpus.zip'

    - name: 'test'
      uri: 'https://www.ncbi.nlm.nih.gov/CBBresearch/Dogan/DISEASE/NCBItestset_corpus.zip'

nlm-chem:
  data_files:
    - name: 'folder'
      uri: 'https://ftp.ncbi.nlm.nih.gov/pub/lu/BC7-NLM-Chem-track/BC7T2-NLMChem-corpus_v2.BioC.xml.gz'

nlm-gene:
  data_files:
    - name: 'folder'
      uri: 'https://zenodo.org/record/5089049/files/NLM-Gene-Corpus.zip'

gnormplus:
  data_files:
    - name: 'folder'
      uri: 'https://www.ncbi.nlm.nih.gov/CBBresearch/Lu/Demo/tmTools/download/GNormPlus/GNormPlusCorpus.zip'

linnaeus:
  data_files:
    - name: 'folder'
      uri: 'https://sourceforge.net/projects/linnaeus/files/Corpora/manual-corpus-species-1.1.tar.gz'

s800:
  data_files:
    - name: 'folder'
      uri: 'https://species.jensenlab.org/files/S800-1.0.tar.gz'

s1000:
  data_files: 
    - name: 'folder'
      uri: 'https://jensenlab.org/assets/s1000/S1000-corpus.tar.gz'
      # uri: 'https://zenodo.org/records/7064902/files/S1000-corpus.tar.gz' # no .txt files

medmentions:
  data_files:
    - name: 'folder'
      uri: 'https://github.com/chanzuckerberg/MedMentions/archive/refs/heads/master.zip'

biored:
  data_files:
    - name: 'folder'
      uri: 'https://ftp.ncbi.nlm.nih.gov/pub/lu/BioRED/BIORED.zip'

tmvar3:
  data_files:
    - name: 'file'
      uri: 'https://ftp.ncbi.nlm.nih.gov/pub/lu/tmVar3/tmVar3Corpus.txt'

osiris:
  data_files:
    - name: 'file'
      uri: 'https://raw.githubusercontent.com/rockt/SETH/master/resources/OSIRIS/corpus.xml'

snp:
  data_files:
    - name: 'folder'
      uri: 'https://www.scai.fraunhofer.de/content/dam/scai/de/downloads/bioinformatik/normalization-variation-corpus.gz'
